# Server configuration
SECRET_KEY="t8hrNO6ibFODgZWxhunyhQ"
FRONTEND_ENDPOINT="<FRONTEND_URL>"

# Database configuration
DATABASE_URL='<DATABASE_URL>'

# Email configuration
MAIL_SERVER='<MAIL_SERVER>'
MAIL_PORT='<MAIL_PORT_NUMBER>'
MAIL_USE_TLS=1
RECIPIENT_GMAIL='<GMAIL_ACCOUNT>'
GMAIL_PASSWORD='<GMAIL_PASSWORD>'

# API configuration
ACCESS_TOKEN='<TMBD_ACCESS_TOKEN>'

