"""Add MovieState model.

Revision ID: 23461a7610be
Revises: 02c4aad5dfb5
Create Date: 2024-08-06 10:17:09.130184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23461a7610be'
down_revision = '02c4aad5dfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_states')
    # ### end Alembic commands ###
